name: robostack
channels:
  - conda-forge
  - robostack
dependencies:
  - python=3.9
  # - nodejs=14
  - nodejs
  - jupyterlab
  - ipympl
  - matplotlib
  - isort
  - numpy
  - pandas
  - scipy
  - rise
  - ipyvuetify
  - bqplot
  - ipywidgets
  - ipycanvas
  - pyyaml
  - requests
  - fuzzywuzzy
  - nbgrader
  - voila
  # ROS
  - ros-noetic-ros-core
  - ros-noetic-rospy
  - ros-noetic-rosbridge-suite
  - ros-noetic-rosbag
  - ros-noetic-rosauth
  - ros-noetic-tf2-web-republisher
  - robostack::jupyterlab-ros
  - robostack::jupyter-amphion
  - robostack::jupyter-ros
  - robostack::jupyter-urdf
  # ML
  - tensorflow
  - pytorch
  # extension
  - jupyterlab-kernelspy
  - jupyterlab-system-monitor
  - jupyterlab-topbar
  - jupyterlab-git
  - jupyterlab_execute_time
  - jupyterlab_code_formatter
  - jupyterlab_latex
  - jupyterlab_genv
  - jupyterlab_templates
  - jupyterlab-drawio
  - pip
  - pip:
      - nbgitpuller
      - jupyros
